### ISSUE TITLE
Failing to parse RDF/XML with 'rdfxml-streaming-parser''?

### ISSUE THREAD

**Issue by pmcb55** [rdf-ext/rdf-ext#82]
The Rdf-Ext documentation specifically states: At the time writing there is no RDF/XML serializer available, as the last sentence here: https://github.com/rdf-ext/documentation#serialize-triples. 

I assume this documentation is just out-of-date, as I'm trying to use Ruben Taelman's RDF/XML parser (with a simple test case below), but it fails with:
```
[pmcb55-ThinkPad-P72: test]$ node index.js
(node:18104) UnhandledPromiseRejectionWarning: TypeError: parser.import is not a function
    at Parsers.import (/home/pmcb55/test/node_modules/rdf-ext/lib/parsers.js:33:25)
    at Promise.resolve.then.then (/home/pmcb55/test/node_modules/rdf-fetch-lite/lib/patch-response.js:34:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:18104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[pmcb55-ThinkPad-P72: test]$
```

...here's the code I'm trying (which works fine for the Turtle vocab served up for the OWL vocab):
```
const rdf = require('rdf-ext');
const rdfFetch = require('rdf-fetch-lite');
const N3Parser = require('rdf-parser-n3');
const { RdfXmlParser } = require('rdfxml-streaming-parser');
// const RdfXmlParser = require('rdfxml-streaming-parser');   // This also fails with the same 'TypeError: parser.import is not a function' !

const formats = {
    parsers: new rdf.Parsers({
        'text/turtle': N3Parser,
        'application/rdf+xml': RdfXmlParser
    }),
};


const resourceRdf = 'http://www.w3.org/2011/http-headers';
const resourceTurtle = 'http://www.w3.org/2002/07/owl#';

// const resourceFile = resourceTurtle; // Works fine!
const resourceFile = resourceRdf;        // Fails!


rdfFetch(resourceFile, { formats })
    .then(resource => {
        return resource.dataset();
    })
    .then(dataset => {
        console.log(`Dataset file: [${resourceFile}]:`);
        console.log(dataset.toString());
    });
```
I'm sure I'm doing something stoopidly wrong here - but any idea what...?!
(NOTE: I'll try and contact Ruben Taelman directly too).

**Comment by bergos** [comment]
You are using the parser, there is still no serializer available.

First of all, please switch from/to:
- rdf-parser-n3 -> @rdfjs/parser-n3
- rdf-fetch-lite -> @rdfjs/fetch-lite

I don't remember if I also fixed some bugs in the meantime, but the API changed a little bit.

You were already very close to the solution. The old RDF-Ext parsers had static `.import` methods. That's why it's working with the `rdf-parser-n3` package. Now you always have to create an instance of the parser first.

So I think you only have to change the part where you create the formats:

```js
const formats = {
    parsers: new rdf.Parsers({
        'text/turtle': new N3Parser(),
        'application/rdf+xml': new RdfXmlParser()
    }),
};
```

Also you have to provide a factory to create the dataset in your fetch (API change in the @rdfjs package):

```js
rdfFetch(resourceFile, { factory: rdf, formats })
```

**Comment by udp** [comment]
> You are using the parser, there is still no serializer available.

[I wrote one some time ago](https://github.com/ICO2S/rdf-serializer-xml) and you added it to the wiki. :-) It hasn't been updated since 2016 but unless the interface specification has changed, it should still work.

**Comment by bergos** [comment]
@udp sorry, there too many package to keep them all in my mind. But actually the interface changed in the meantime. Would be great if you can upgrade it to implement the RDFJS specification and also put it on the [RDFJS page](http://rdf.js.org/). If you need some help, just ask in the [RDFJS Gitter channel](https://gitter.im/rdfjs/public).

**Comment by rubensworks** [comment]
Indeed, as @bergos has said, the RDF/XML parser needs to be instantiated before it is passed to the collection of parsers.

For reference, these are the config options that can be passed to the constructor: https://github.com/rdfjs/rdfxml-streaming-parser.js#configuration

**Comment by pmcb55** [comment]
Thanks for the guidance - but I'm still having problems though. Also I can't seem to find any guiding documentation. E.g. both 'http://rdf.js.org/data-model/' and 'http://rdf.js.org/dataset/' give me 404's.

Also, previously I used the Examples repo under Rdf-Ext (https://github.com/rdf-ext/rdf-examples) to learn Rdf-Ext, but all the examples in there still seem to be using the 'old' API. Are there any equivalent Examples showing how to use the 'new APIs'...? I can't see anything under 'http://rdf.js.org/' or 'https://github.com/rdfjs'.

Here's my test code now:
```
// const rdf = require('rdf-ext');
const rdf = require('@rdfjs/data-model');
const rdfFetch = require('@rdfjs/fetch-lite');
const N3Parser = require('@rdfjs/parser-n3');
const RdfXmlParser = require('rdfxml-streaming-parser').RdfXmlParser;

const DataFactory = require('@rdfjs/data-model');

const formats = {
    parsers: new rdf.Parsers({
        'text/turtle': new N3Parser(),
        'application/rdf+xml': new RdfXmlParser()
    })
};

const resourceRdf = 'http://www.w3.org/2011/http-headers';
const resourceTurtle = 'http://www.w3.org/2002/07/owl#';

// const resourceFile = resourceTurtle;
const resourceFile = resourceRdf;


rdfFetch(resourceFile, { factory: rdf, formats })
    .then(resource => {
        return resource.dataset();
    })
    .then(dataset => {
        console.log(`Dataset file: [${resourceFile}]:`);
        console.log(dataset.toString());
    });
```
..but now I can't even get past the parser config...
```
/home/pmcb55/test/index.js:10
    parsers: new rdf.Parsers({
             ^

TypeError: rdf.Parsers is not a constructor
    at Object.<anonymous> (/home/pmcb55/test/index.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

In the above code, I assumed I should also replace `require('rdf-ext')` with `require('@rdfjs/data-model')` (but I'm guessing there!?). If I continue to use `require('rdf-ext')`, I get this error:
```
[pmcb55-ThinkPad-P72: test]$ node index.js 
/home/pmcb55/test/node_modules/@rdfjs/fetch-lite/lib/patchRequest.js:9
  options.headers.accept = options.headers.accept || [...formats.parsers.keys()].join(', ')
                                                                         ^

TypeError: formats.parsers.keys(...) is not a function or its return value is not iterable
    at patchRequest (/home/pmcb55/test/node_modules/@rdfjs/fetch-lite/lib/patchRequest.js:9:74)
    at rdfFetch (/home/pmcb55/test/node_modules/@rdfjs/fetch-lite/index.js:14:13)
    at Object.<anonymous> (/home/pmcb55/test/index.js:23:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

Here's my package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@rdfjs/data-model": "^1.1.2",
    "@rdfjs/fetch-lite": "^2.0.1",
    "@rdfjs/parser-n3": "^1.1.3",
    "rdf-ext": "^1.3.0",
    "rdfxml-streaming-parser": "^1.3.1"
  }
}
```

**Comment by pmcb55** [comment]
@bergos Hi Thomas - sorry to hassle you directly, but Ruben tells me he's not familiar enough with Rdf-Ext to see where I'm going wrong now. I tried your suggestions, but clearly I'm still missing something stoopid :) ! I'm hoping my updated test case above should make it easy to see where I'm going wrong...

**Comment by bergos** [comment]
@pmcb55 I changed the code like below and it's working now. `rdf.Parsers` became `SinkMap`, which is now a separate package, so you have to install also `@rdfjs/sink-map`.

Where did you find the dead data-model and dataset links? The URLs changed to http://rdf.js.org/data-model-spec/ and https://rdf.js.org/dataset-spec/. If there are still some old URLs somewhere, we should update them. Would be great if you could open an issue or PR directly at the related repo.

```js
const rdf = require('rdf-ext')
const rdfFetch = require('@rdfjs/fetch-lite')
const N3Parser = require('@rdfjs/parser-n3')
const SinkMap = require('@rdfjs/sink-map')
const RdfXmlParser = require('rdfxml-streaming-parser').RdfXmlParser

const formats = {
  parsers: new SinkMap([
    ['text/turtle', new N3Parser()],
    ['application/rdf+xml', new RdfXmlParser()]
  ])
}

const resourceRdf = 'http://www.w3.org/2011/http-headers'
const resourceTurtle = 'http://www.w3.org/2002/07/owl#'

// const resourceFile = resourceTurtle
const resourceFile = resourceRdf

rdfFetch(resourceFile, { factory: rdf, formats })
  .then(resource => {
    return resource.dataset()
  })
  .then(dataset => {
    console.log(`Dataset file: [${resourceFile}]:`)
    console.log(dataset.toString())
  })
```

**Comment by pmcb55** [comment]
Thanks so much @bergos - all working correctly for me now! (BTW, I've no idea now how I came across those old specification URI's - they must have been from just clicking around aimlessly, sorry!)

Separately, I also had to transition from `rdf-formats-common` to `@rdfjs/formats-common`, but that was pretty straightforward.

But in terms of documenting all these changes (e.g. the introduction of `SinkMap`), where is any of that documented (because I couldn't find anything at all)? The two links you provide to the specs (e.g.   http://rdf.js.org/data-model-spec/ and https://rdf.js.org/dataset-spec/) are fine as reference info, but is there anything anywhere that explains in a tutorial form how to use RdfJs?

For example, for `@rdfjs/formats-common`, I couldn't find any descriptive documentation anywhere, e.g. there is nothing (that I can find anyway) on http://rdf.js.org/. I just happened to stumble across it when clicking around and found myself at https://github.com/rdfjs-base, and scrolling down through the list of repositories there I just happened to notice `formats-common`, which only jumped out at me 'cos I was familiar with the old `rdf-formats-common`.

I guess what I'm really missing is an updated version of the Examples repo (i.e. https://github.com/rdf-ext/rdf-examples), or at a minimum an updated version of the old 'documentation': https://github.com/rdf-ext/documentation.

And shouldn't there be at least some link or indication on https://github.com/rdfjs that https://github.com/rdfjs-base exists, and that explains the differences, and the relationships between, these two Github organisations?

**Comment by ktk** [comment]
@pmcb55 yes we definitely need to improve documentation. We did an update to the README and link to the recent packages now. For the other repos (documentation and examples), we are not yet sure where we will document it in what form, we currently discuss that.

In general the idea is that people can include rdf-ext and they get a working env with up-to-date libraries. That got a lot better in the past weeks.

**Comment by ktk** [comment]
Closing here, some missing things for documentation linked in doc-issue above.
